apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minifiles
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Siyam-A-S/minifiles.git
    targetRevision: main
    path: deploy/k8s/overlays/azure
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
